/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* SysInt_1ms */
#define SysInt_1ms__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_1ms__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_1ms__INTC_NUMBER 90u
#define SysInt_1ms_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_1ms_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_1ms_INTC_NUMBER 90u

/* RTC_RTC_IRQ */
#define RTC_RTC_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define RTC_RTC_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define RTC_RTC_IRQ__INTC_NUMBER 21u
#define RTC_RTC_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define RTC_RTC_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define RTC_RTC_IRQ_INTC_NUMBER 21u

/* I2C_1_SCB_IRQ */
#define I2C_1_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define I2C_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define I2C_1_SCB_IRQ__INTC_NUMBER 44u
#define I2C_1_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define I2C_1_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define I2C_1_SCB_IRQ_INTC_NUMBER 44u

/* UART_1_SCB_IRQ */
#define UART_1_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define UART_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define UART_1_SCB_IRQ__INTC_NUMBER 46u
#define UART_1_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define UART_1_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define UART_1_SCB_IRQ_INTC_NUMBER 46u

/* SysInt_ImuDataReadyINT */
#define SysInt_ImuDataReadyINT__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_ImuDataReadyINT__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_ImuDataReadyINT__INTC_NUMBER 122u
#define SysInt_ImuDataReadyINT_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_ImuDataReadyINT_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_ImuDataReadyINT_INTC_NUMBER 122u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
