/*******************************************************************************
* File Name: cyfitter_sysint_cfg.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_CFG_H
#define INCLUDED_CYFITTER_SYSINT_CFG_H

#include "sysint/cy_sysint.h"

/* ARM CM4 */
#if (((__CORTEX_M == 4) && (CY_CORE_ID == 0)))
    #define isr_gpio__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t isr_gpio_cfg;

    #define CY_EINK_SPIM_SCB_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t CY_EINK_SPIM_SCB_IRQ_cfg;

    #define CapSense_ISR__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t CapSense_ISR_cfg;

    #define ADC_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t ADC_IRQ_cfg;

#endif /* ((__CORTEX_M == 4) && (CY_CORE_ID == 0)) */

/* ARM CM0+ */
#if (((__CORTEX_M == 0) && (CY_CORE_ID == 0)))
    #define BLE_bless_isr__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t BLE_bless_isr_cfg;

#endif /* ((__CORTEX_M == 0) && (CY_CORE_ID == 0)) */


#endif /* INCLUDED_CYFITTER_SYSINT_CFG_H */
