/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* LED_B */
#define LED_B_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_B_0_INBUF_ENABLED 0u
#define LED_B_0_INIT_DRIVESTATE 1u
#define LED_B_0_INIT_MUXSEL 0u
#define LED_B_0_INPUT_SYNC 2u
#define LED_B_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_B_0_NUM 1u
#define LED_B_0_PORT GPIO_PRT11
#define LED_B_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_B_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_B_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_B_INBUF_ENABLED 0u
#define LED_B_INIT_DRIVESTATE 1u
#define LED_B_INIT_MUXSEL 0u
#define LED_B_INPUT_SYNC 2u
#define LED_B_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_B_NUM 1u
#define LED_B_PORT GPIO_PRT11
#define LED_B_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_B_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED_G */
#define LED_G_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_G_0_INBUF_ENABLED 0u
#define LED_G_0_INIT_DRIVESTATE 1u
#define LED_G_0_INIT_MUXSEL 0u
#define LED_G_0_INPUT_SYNC 2u
#define LED_G_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_G_0_NUM 1u
#define LED_G_0_PORT GPIO_PRT1
#define LED_G_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_G_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_G_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_G_INBUF_ENABLED 0u
#define LED_G_INIT_DRIVESTATE 1u
#define LED_G_INIT_MUXSEL 0u
#define LED_G_INPUT_SYNC 2u
#define LED_G_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_G_NUM 1u
#define LED_G_PORT GPIO_PRT1
#define LED_G_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_G_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED_R */
#define LED_R_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_R_0_INBUF_ENABLED 0u
#define LED_R_0_INIT_DRIVESTATE 1u
#define LED_R_0_INIT_MUXSEL 0u
#define LED_R_0_INPUT_SYNC 2u
#define LED_R_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_R_0_NUM 3u
#define LED_R_0_PORT GPIO_PRT0
#define LED_R_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_R_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_R_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_R_INBUF_ENABLED 0u
#define LED_R_INIT_DRIVESTATE 1u
#define LED_R_INIT_MUXSEL 0u
#define LED_R_INPUT_SYNC 2u
#define LED_R_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_R_NUM 3u
#define LED_R_PORT GPIO_PRT0
#define LED_R_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_R_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* I2C_1_scl */
#define I2C_1_scl_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_1_scl_0_INBUF_ENABLED 1u
#define I2C_1_scl_0_INIT_DRIVESTATE 1u
#define I2C_1_scl_0_INIT_MUXSEL 19u
#define I2C_1_scl_0_INPUT_SYNC 2u
#define I2C_1_scl_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_1_scl_0_NUM 0u
#define I2C_1_scl_0_PORT GPIO_PRT6
#define I2C_1_scl_0_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_1_scl_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define I2C_1_scl_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_1_scl_INBUF_ENABLED 1u
#define I2C_1_scl_INIT_DRIVESTATE 1u
#define I2C_1_scl_INIT_MUXSEL 19u
#define I2C_1_scl_INPUT_SYNC 2u
#define I2C_1_scl_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_1_scl_NUM 0u
#define I2C_1_scl_PORT GPIO_PRT6
#define I2C_1_scl_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_1_scl_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* I2C_1_sda */
#define I2C_1_sda_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_1_sda_0_INBUF_ENABLED 1u
#define I2C_1_sda_0_INIT_DRIVESTATE 1u
#define I2C_1_sda_0_INIT_MUXSEL 19u
#define I2C_1_sda_0_INPUT_SYNC 2u
#define I2C_1_sda_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_1_sda_0_NUM 1u
#define I2C_1_sda_0_PORT GPIO_PRT6
#define I2C_1_sda_0_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_1_sda_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define I2C_1_sda_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_1_sda_INBUF_ENABLED 1u
#define I2C_1_sda_INIT_DRIVESTATE 1u
#define I2C_1_sda_INIT_MUXSEL 19u
#define I2C_1_sda_INPUT_SYNC 2u
#define I2C_1_sda_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_1_sda_NUM 1u
#define I2C_1_sda_PORT GPIO_PRT6
#define I2C_1_sda_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_1_sda_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_rx */
#define UART_1_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_0_INBUF_ENABLED 1u
#define UART_1_rx_0_INIT_DRIVESTATE 1u
#define UART_1_rx_0_INIT_MUXSEL 18u
#define UART_1_rx_0_INPUT_SYNC 2u
#define UART_1_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_0_NUM 0u
#define UART_1_rx_0_PORT GPIO_PRT5
#define UART_1_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_INBUF_ENABLED 1u
#define UART_1_rx_INIT_DRIVESTATE 1u
#define UART_1_rx_INIT_MUXSEL 18u
#define UART_1_rx_INPUT_SYNC 2u
#define UART_1_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_NUM 0u
#define UART_1_rx_PORT GPIO_PRT5
#define UART_1_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_tx */
#define UART_1_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_0_INBUF_ENABLED 0u
#define UART_1_tx_0_INIT_DRIVESTATE 1u
#define UART_1_tx_0_INIT_MUXSEL 18u
#define UART_1_tx_0_INPUT_SYNC 2u
#define UART_1_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_0_NUM 1u
#define UART_1_tx_0_PORT GPIO_PRT5
#define UART_1_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_INBUF_ENABLED 0u
#define UART_1_tx_INIT_DRIVESTATE 1u
#define UART_1_tx_INIT_MUXSEL 18u
#define UART_1_tx_INPUT_SYNC 2u
#define UART_1_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_NUM 1u
#define UART_1_tx_PORT GPIO_PRT5
#define UART_1_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_ImuDataReady_INT */
#define Pin_ImuDataReady_INT_0_DRIVEMODE CY_GPIO_DM_PULLDOWN
#define Pin_ImuDataReady_INT_0_INBUF_ENABLED 1u
#define Pin_ImuDataReady_INT_0_INIT_DRIVESTATE 0u
#define Pin_ImuDataReady_INT_0_INIT_MUXSEL 0u
#define Pin_ImuDataReady_INT_0_INPUT_SYNC 2u
#define Pin_ImuDataReady_INT_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_ImuDataReady_INT_0_NUM 1u
#define Pin_ImuDataReady_INT_0_PORT GPIO_PRT13
#define Pin_ImuDataReady_INT_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_ImuDataReady_INT_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_ImuDataReady_INT_DRIVEMODE CY_GPIO_DM_PULLDOWN
#define Pin_ImuDataReady_INT_INBUF_ENABLED 1u
#define Pin_ImuDataReady_INT_INIT_DRIVESTATE 0u
#define Pin_ImuDataReady_INT_INIT_MUXSEL 0u
#define Pin_ImuDataReady_INT_INPUT_SYNC 2u
#define Pin_ImuDataReady_INT_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_ImuDataReady_INT_NUM 1u
#define Pin_ImuDataReady_INT_PORT GPIO_PRT13
#define Pin_ImuDataReady_INT_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_ImuDataReady_INT_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
