/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* ADC_IRQ */
#define ADC_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define ADC_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define ADC_IRQ__INTC_NUMBER 138u
#define ADC_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define ADC_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define ADC_IRQ_INTC_NUMBER 138u

/* isr_gpio */
#define isr_gpio__INTC_CORTEXM4_ASSIGNED 1
#define isr_gpio__INTC_CORTEXM4_PRIORITY 6u
#define isr_gpio__INTC_NUMBER 0u
#define isr_gpio_INTC_CORTEXM4_ASSIGNED 1
#define isr_gpio_INTC_CORTEXM4_PRIORITY 6u
#define isr_gpio_INTC_NUMBER 0u

/* BLE_bless_isr */
#define BLE_bless_isr__INTC_CORTEXM0P_ASSIGNED 1
#define BLE_bless_isr__INTC_CORTEXM0P_MUX 3u
#define BLE_bless_isr__INTC_CORTEXM0P_PRIORITY 1u
#define BLE_bless_isr__INTC_NUMBER 24u
#define BLE_bless_isr_INTC_CORTEXM0P_ASSIGNED 1
#define BLE_bless_isr_INTC_CORTEXM0P_MUX 3u
#define BLE_bless_isr_INTC_CORTEXM0P_PRIORITY 1u
#define BLE_bless_isr_INTC_NUMBER 24u

/* CY_EINK_SPIM_SCB_IRQ */
#define CY_EINK_SPIM_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define CY_EINK_SPIM_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define CY_EINK_SPIM_SCB_IRQ__INTC_NUMBER 47u
#define CY_EINK_SPIM_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define CY_EINK_SPIM_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define CY_EINK_SPIM_SCB_IRQ_INTC_NUMBER 47u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
