# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\codyg\git\psoc6-realtime-processing\BLE_RTC_IMU.cydsn\CE218138_BLE_Thermometer_RTOS01.cydsn\CE218138_BLE_Thermometer_RTOS01.cyprj
# Date: Fri, 30 Oct 2020 15:43:41 GMT
#set_units -time ns
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyClk_LF} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyFLL} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/fll}]]
create_clock -name {CyClk_HF0} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk_0}]]
create_clock -name {CyClk_Fast} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/fastclk}]]
create_clock -name {CyClk_Peri} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/periclk}]]
create_generated_clock -name {CyClk_Slow} -source [get_pins {ClockBlock/periclk}] -edges {1 2 3} [list [get_pins {ClockBlock/slowclk}]]
create_generated_clock -name {ADC_intSarClock} -source [get_pins {ClockBlock/periclk}] -edges {1 25 49} [list [get_pins {ClockBlock/ff_div_49}]]
create_generated_clock -name {Clock_1khz} -source [get_pins {ClockBlock/periclk}] -edges {1 24001 48001} [list [get_pins {ClockBlock/ff_div_11}] [get_pins {ClockBlock/ff_div_12}] [get_pins {ClockBlock/ff_div_13}]]
create_generated_clock -name {DEBUG_UART_SCBCLK} -source [get_pins {ClockBlock/periclk}] -edges {1 27 53} -nominal_period 1083.3333333333333 [list [get_pins {ClockBlock/ff_div_5}]]
create_generated_clock -name {CY_EINK_SPIM_SCBCLK} -source [get_pins {ClockBlock/periclk}] -edges {1 2 3} [list [get_pins {ClockBlock/ff_div_6}]]
create_clock -name {CyPeriClk_App} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/periclk_App}]]
create_clock -name {CyIMO} -period 125 -waveform {0 62.5} [list [get_pins {ClockBlock/imo}]]


# Component constraints for C:\Users\codyg\git\psoc6-realtime-processing\BLE_RTC_IMU.cydsn\CE218138_BLE_Thermometer_RTOS01.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\codyg\git\psoc6-realtime-processing\BLE_RTC_IMU.cydsn\CE218138_BLE_Thermometer_RTOS01.cydsn\CE218138_BLE_Thermometer_RTOS01.cyprj
# Date: Fri, 30 Oct 2020 15:43:21 GMT
